name: vid2slides
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - contourpy=1.0.7
  - cycler=0.11.0
  - ffmpeg=4.3.1
  - fonttools=4.39.4
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - importlib_resources=5.12.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - leptonica=1.82.0
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=23.1
  - pip=20.2.2
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.8.5
  - python-dateutil=2.8.2
  - python_abi=3.8
  - readline=8.2
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.39.3
  - tesseract=4.1.1
  - tk=8.6.12
  - tornado=6.3.2
  - unicodedata2=15.0.0
  - wheel=0.38.4
  - x264=1!152.20180806
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.10
  - zipp=3.15.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - charset-normalizer==3.1.0
    - decorator==4.4.2
    - decord==0.5.0
    - ffmpeg-python==0.2.0
    - future==0.18.3
    - idna==3.4
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - joblib==1.2.0
    - moviepy==1.0.3
    - numpy==1.24.3
    - opencv-python==4.4.0.46
    - pillow==9.5.0
    - proglog==0.1.10
    - pytesseract==0.3.6
    - requests==2.31.0
    - scikit-learn==0.23.2
    - scipy==1.10.1
    - threadpoolctl==3.1.0
    - tqdm==4.65.0
    - urllib3==2.0.2
